### ISSUE TITLE
Wrong manifest file read

### ISSUE THREAD

**Issue by frederikhegger** [triologygmbh/versionName#1]
I experienced a problem, when using getVersionNameFromManifest() in combination with a JAR. Then unfortunately, a META-INF/MANIFEST.MF from the classpath is read, and not the one from the actual package which includes the "versionName".

In my simple example the META-INF/MANIFEST.MF from sun.net.www.protocol.jar.JarURLConnection:jar:file:/C:/Program%20Files/Java/jdk1.8.0_172/jre/lib/charsets.jar!/META-INF/MANIFEST.MF is read and thus does not find the key "versionName".

The problem can be tracked down to the code part where the manifest is read using the classloader:

https://github.com/triologygmbh/versionName/blob/d36a6c2e7bf6d35597adb54779d383f63de332b6/versionName/src/main/java/de/triology/versionname/VersionNames.java#L72
https://github.com/triologygmbh/versionName/blob/d36a6c2e7bf6d35597adb54779d383f63de332b6/versionName/src/main/java/de/triology/versionname/VersionNames.java#L201

**Comment by schnatterer** [comment]
Could you provide some more info?

- How can this reproduced?   
There is a JAR example [in the repo](https://github.com/triologygmbh/versionName/tree/develop/examples/jar). What did you do differently for your issue to occur?
- What JDK are you on?

**Comment by frederikhegger** [comment]
I can reproduce it using the example from your repository and JDK 1.8.0_172:

![grafik](https://user-images.githubusercontent.com/555675/54597013-11de9500-4a36-11e9-8166-d3c70af1b11a.png)

**Comment by schnatterer** [comment]
Thanks, I'll look into it and get back once I know more.

**Comment by schnatterer** [comment]
That's a tough one!
Could not reproduce the issue with oracle JDK neither locally, nor on [our jenkins](https://opensource.triology.de/jenkins/job/triologygmbh-github/job/versionName/job/develop/35/console), which ran on Oracle JDK 8u 202.

I could however reproduce your issue with docker:
```bash
docker run --rm -it -v $(pwd):/app piegsaj/oracle-jre:1.8.0_102-b14 java -jar /app/examples/jar/target/jar-1.0.3-SNAPSHOT-jar-with-dependencies.jar
1.0.3-SNAPSHOT (2019-03-21T09:43:49Z, branch develop, commit d36a6c2)
docker run --rm -it -v $(pwd):/app openjdk:8u102-jre java -jar /app/examples/jar/target/jar-1.0.3-SNAPSHOT-jar-with-dependencies.jar
```
Where the second command did not return anything.
So let me guess: You're running OpenJDK? Another option is that this issue is Windows-related.

Anyways, I implemented a proof of concept that fixed the issue for my docker test stated above.

Don't know if this fixes the issue on your side as well. So could you please validate this
* by checking out, building and running the `develop` branch or e2ecd21?
* Alternatively, you could use the versionName jar SNAPSHOT dependency from [here](https://oss.sonatype.org/content/repositories/snapshots/de/triology/versionName/jar/1.0.3-SNAPSHOT/jar-1.0.3-20190322.124012-9-jar-with-dependencies.jar).

**Comment by frederikhegger** [comment]
Actually, I am using the Oracle JDK. Strange though.

I am going to try your changes today and come back to you then.

In any case, thanks for fast reply.

**Comment by frederikhegger** [comment]
I can confirm that your changes made it working also for my machines and configurations.

Thanks a lot.

Will you prepare the release soon?

**Comment by schnatterer** [comment]
I will create a new release in the next couple of days.
While I'm on it, this repo will be moved to a new home @cloudogu, which will most likely result in new maven coordinates and package names.
I suggest you use GitHub's watch feature for releases.

**Comment by frederikhegger** [comment]
Perfect. Thanks a lot for the quick fix and info about the upcoming move.
